spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vaadin?useSSL=false&useUnicode=true
    username: root
    password: 123456
    schema:
      - classpath:mysql/cars.sql